function tests = test_scripts
% TEST_SCRIPTS  End-to-end smoke tests for the three ported entry points:
% run_optimization, compare_classical, manual_weights_render. Each runs on a
% small/fast configuration and must produce its expected output files with
% sane (finite) metrics.
tests = functiontests(localfunctions);
end


function setupOnce(testCase)
here = fileparts(mfilename('fullpath'));
addpath(fullfile(fileparts(here), 'matlab_utils'));
root = fileparts(fileparts(here));
testCase.TestData.root    = root;
testCase.TestData.dataDir = fullfile(root, 'data', 'spacing0.6');
work = fullfile(tempdir, ['matlab_script_test_' char(java.util.UUID.randomUUID)]);
mkdir(work);
testCase.TestData.work = work;
testCase.TestData.cleanupDirs = {};
end


function teardownOnce(testCase)
if isfolder(testCase.TestData.work)
    rmdir(testCase.TestData.work, 's');
end
for i = 1:numel(testCase.TestData.cleanupDirs)
    d = testCase.TestData.cleanupDirs{i};
    if isfolder(d), rmdir(d, 's'); end
end
end


function write_lines(path, lines)
fid = fopen(path, 'w');
for i = 1:numel(lines)
    fprintf(fid, '%s\n', lines{i});
end
fclose(fid);
end


function test_run_optimization(testCase)
work    = testCase.TestData.work;
dataDir = testCase.TestData.dataDir;
resDir  = fullfile(work, 'results');
cfgPath = fullfile(work, 'cfg_run.yaml');

write_lines(cfgPath, { ...
    ['element_patterns_dir: "' dataDir '"'], ...
    'polarization: "copol"', ...
    'directives:', ...
    '  - type: "peak"', ...
    '    theta: 0.0', ...
    '    phi: 0.0', ...
    '    theta_width: 20.0', ...
    '    phi_width: 20.0', ...
    '    weight: 1.0', ...
    'optimizer:', ...
    '  max_iterations: 20', ...
    '  cost_tolerance: 1.0e-6', ...
    '  n_restarts: 1', ...
    '  amplitude_bounds: [0.0, 1.0]', ...
    '  use_uniform_init: true', ...
    '  use_single_element_init: false', ...
    'output:', ...
    ['  results_dir: "' resDir '"'], ...
    '  plot_cut_type: "auto"', ...
    '  plot_dynamic_range_db: 40', ...
    '  save_polar_plot: true', ...
    '  save_cartesian_plot: true', ...
    '  save_2d_projection_plot: true', ...
    '  save_weight_plots: true', ...
    '  save_cost_history_plot: true', ...
    '  plot_equal_area: false', ...
    '  save_pattern_gif: false', ...
    });

output_dir = run_optimization(cfgPath);

% Output files exist.
for f = {'weights.csv','metrics.json','run_report.txt','config.yaml', ...
         'pattern_polar.png','pattern_cartesian.png','pattern_2d.png', ...
         'weights.png','cost_history.png'}
    verifyTrue(testCase, isfile(fullfile(output_dir, f{1})), sprintf('missing %s', f{1}));
end

% weights.csv has one row per element (16) + sane metrics.json.
T = readtable(fullfile(output_dir, 'weights.csv'));
verifyEqual(testCase, height(T), 16);

m = jsondecode(fileread(fullfile(output_dir, 'metrics.json')));
verifyTrue(testCase, isfinite(m.global_peak_dbi));
verifyTrue(testCase, isnumeric(m.iteration_count));
verifyTrue(testCase, numel(m.directive_metrics) == 1);
end


function test_compare_classical(testCase)
work    = testCase.TestData.work;
cfgPath = fullfile(work, 'cfg_compare.yaml');

write_lines(cfgPath, { ...
    'n_side: 3', ...
    'd_over_lambda: 0.5', ...
    'theta_step_deg: 10.0', ...
    'phi_step_deg: 30.0', ...
    'element_source: "synthetic"', ...
    'polarization: "copol"', ...
    'n_restarts: 1', ...
    'max_iterations: 30', ...
    'cost_tolerance: 1.0e-9', ...
    'plot_dynamic_range_db: 60', ...
    'scenarios:', ...
    '  - label: "Smoke"', ...
    '    steer_theta_deg: 0.0', ...
    '    steer_phi_deg: 0.0', ...
    '    null_theta_deg: 40.0', ...
    '    directives:', ...
    '      - type: "peak"', ...
    '        theta: 0.0', ...
    '        phi: 0.0', ...
    '        theta_width: 20.0', ...
    '        phi_width: 360.0', ...
    '        weight: 1.0', ...
    '      - type: "null"', ...
    '        theta: 40.0', ...
    '        phi: 0.0', ...
    '        theta_width: 10.0', ...
    '        phi_width: 360.0', ...
    '        weight: 2.0', ...
    });

output_dir = compare_classical(cfgPath);
testCase.TestData.cleanupDirs{end + 1} = output_dir;

verifyTrue(testCase, isfile(fullfile(output_dir, 'compare_classical_3x3.png')));
verifyTrue(testCase, isfile(fullfile(output_dir, 'console_output.txt')));
verifyTrue(testCase, isfile(fullfile(output_dir, 'test_config.yaml')));
end


function test_manual_weights_render(testCase)
work    = testCase.TestData.work;
dataDir = testCase.TestData.dataDir;
cfgPath = fullfile(work, 'cfg_manual.yaml');

write_lines(cfgPath, { ...
    ['element_patterns_dir: "' dataDir '"'], ...
    'polarization: "copol"', ...
    'directives:', ...
    '  - type: "peak"', ...
    '    theta: 0.0', ...
    '    phi: 0.0', ...
    '    theta_width: 20.0', ...
    '    phi_width: 20.0', ...
    '    weight: 1.0', ...
    });

% (a) uniform weights path.
out1 = fullfile(work, 'manual_uniform.png');
m1 = manual_weights_render(cfgPath, [], out1);
verifyTrue(testCase, isfile(out1));
verifyTrue(testCase, isfinite(m1.global_peak_dbi));

% (b) weights-CSV path (run_optimization format: element_index,amplitude,phase_deg,real,imag).
csvPath = fullfile(work, 'weights.csv');
fid = fopen(csvPath, 'w');
fprintf(fid, 'element_index,amplitude,phase_deg,real,imag\n');
for n = 0:15
    fprintf(fid, '%d,%.2f,%.2f,%.2f,%.2f\n', n, 1.0, 0.0, 1.0, 0.0);
end
fclose(fid);

out2 = fullfile(work, 'manual_csv.png');
m2 = manual_weights_render(cfgPath, csvPath, out2);
verifyTrue(testCase, isfile(out2));
verifyTrue(testCase, isfinite(m2.global_peak_dbi));
end
